Config = {}
Config.Locale = 'es'

Config.AntiResourceStopCheck = false
Config.AntiResourceStartCheck = false --Se activará si se inicia un nuevo recurso
Config.AntiSpectate = true -- Banea si un jugador usa el modo spectate
Config.AntiBMCGLOBAL = true --Detecta si un jugador ejecuta un executor
Config.AntiCMD = true -- Detecta si un jugador startea otro script o mennu .lua
Config.AntiCheatEngine = true -- Detecta si un jugador usa el Cheat Engine
Config.AntiInyection = true --Banea si un jugador se injecta un menu
Config.AntiInyectionv2 = true --Banea si un jugador se injecta un menu
Config.AntiCheat = true -- Activa el AC
Config.AntiCarDetroy = false --Detecta si un coche esta roto y lo elimina
Config.AntiFirePlayer = true -- Detecta y elimina el fuego
Config.AntiCarRam = false
Config.AntiGodmode = true -- Detecta si un jugador tiene GodMode
Config.AntiBlips = false  -- Detecta si un jugador tiene los blips de los jugadores
Config.PlayerProtection = true -- Proteccion para el jugador de explosiones
Config.AntiPedAttack = false  -- Anti ped con armas
Config.AntiBlackweapons = true
Config.AntiCarBlack    = true --Detecta y elimina si alguien se sube a un coche prohibido
Config.MiniMap         = false --Activa el MiniMapa

-- Detecta si un jugador puso una tecla prohibida
Config.AntiKey       = false
Config.AntiKeyInsert = false
Config.AntiKeyALTF8  = false
Config.AntiKeyShiftG = false
Config.AntiKeyct5rlf8 = false

-- Coches prohibidos - Añadir mas si es necesario.
Config.CarsBL = {
	"cargoplane",
	"cargobob",
	"cargobob2",
	"cargobob3",
	"cargobob4",
	"apc",
	"khanjali",
	"hydra",
	"lazer",
	"minitank",
	"scarab",
	"scarab2",
	"scarab3",
	"thruster",
	"rhino",
	"trailersmall2",
	"barrage",
	"halftrack",
	"akula",
	"technical",
	"technical2",
	"technical3",
	"nightshark",
	"blimp",
	"blimp2",
	"blimp3",
	"ztype",
	"armytanker",
	"armytrailer",
	"armytrailer2",
	"baletrailer",
	"boattrailer",
	"cablecar",
	"docktrailer",
	"freighttrailer",
	"graintrailer",
	"proptrailer",
	"raketrailer",
	"buzzard",
	"tr2",
	"tr3",
	"tr4",
	"trflat",
	"tvtrailer",
	"tanker",
	"tanker2",
	"trailerlarge",
	"trailerlogs",
	"trailersmall",
	"trailers",
	"trailers2",
	"trailers3",
	"trailers4",
	"freight",
	"freightcar",
	"freightcont1",
	"freightcont2",
	"freightgrain",
	"metrotrain",
	"tankercar",
	"alphaz1",
	"avenger",
	"avenger2",
	"bombushka",
	"cuban800",
	"microlight",
	"titan",
	"tula",
	"rogue",
	"duster",
	"mogul",
	"starling",
	"strikeforce"
}
-- Peds prohibidos - Añadir mas si es necesario.
Config.PEDBLACK = {
	"CSB_BallasOG",
	"MP_S_ARMOURED_01",
	"S_F_Y_Cop_01",
	"S_F_Y_Cop_02",
	"S_F_Y_Cop_03",
	"S_M_Y_Cop_01",
	"S_M_Y_Cop_02",
	"S_M_Y_Cop_03",
	"A_C_MtLion",
	"S_F_Y_Sheriff_01",
	"S_F_Y_Sheriff_02",
	"S_F_Y_Sheriff_03",
	"S_M_Y_Marine_01",
	"S_M_Y_Marine_02",
	"S_M_Y_Marine_03",
	"S_M_SECURITY_01",
	"S_M_SECURITY_02",
	"s_m_y_swat_01",
	"a_m_y_mexthug_01",
	"u_m_y_zombie_01",
	"S_M_SECURITY_03",
	"s_m_y_swat_01",
	"S_M_Y_ARMYMECH_01",
	"S_M_Y_ARMYMECH_02",
	"S_M_Y_ARMYMECH_03",
	"S_M_Y_BLACKOPS_01",
	"S_M_Y_BLACKOPS_02",
	 "S_M_Y_BLACKOPS_03"
}
-- Armas prohibidos
Config.WeaponBL={
	--"WEAPON_GOLFCLUB",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_GRENADELAUNCHER_SMOKE",
	"WEAPON_RPG",
	--"WEAPON_MOLOTOV",
	--"WEAPON_SNOWBALL",
	"WEAPON_PIPEBOMB",
--	"WEAPON_COMBATMG_MK2",
	"WEAPON_STINGER",
	"WEAPON_MINIGUN",
	"WEAPON_GARBAGEBAG",
	"WEAPON_RAILGUN",
	"WEAPON_RAILPISTOL",
--	"WEAPON_POOLCUE",
--	"WEAPON_STONE_HATCHET",
	--"WEAPON_PISTOL50",
	--"WEAPON_SNSPISTOL",
	--"WEAPON_SNSPISTOL_MK2",
	--"WEAPON_VINTAGEPISTOL",
	--"WEAPON_MARKSMANPISTOL",
	--"WEAPON_REVOLVER",
	--"WEAPON_REVOLVER_MK2",
	--"WEAPON_CERAMICPISTOL",
	--"WEAPON_MUSKET",
	--"WEAPON_DBSHOTGUN",
	--"WEAPON_AUTOSHOTGUN",
	--"WEAPON_MACHINEPISTOL",
	--"WEAPON_NAVYREVOLVER",
	"WEAPON_RAYCARBINE", 
	"WEAPON_RAYMINIGUN",
	--"WEAPON_DIGISCANNER",
	--"WEAPON_BULLPUPRIFLE_MK2",
	--"WEAPON_PUMPSHOTGUN_MK2",
	--"WEAPON_MARKSMANRIFLE_MK2",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_HOMINGLAUNCHER"
}
-- Objetos prohibidos
Config.ObjectsBL={
	"stt_prop_stunt_bblock_huge_01",
	"stt_prop_stunt_bblock_huge_02",
	"stt_prop_stunt_bblock_huge_03",
	"stt_prop_stunt_bblock_huge_04",
	"stt_prop_stunt_bblock_huge_05",
	"stt_prop_stunt_bblock_hump_01",
	"stt_prop_stunt_bblock_hump_02",
	"stt_prop_stunt_bblock_lrg1",
	"stt_prop_stunt_bblock_lrg2",
	"stt_prop_stunt_bblock_lrg3",
	"stt_prop_stunt_bblock_mdm1",
	"stt_prop_stunt_bblock_mdm2",
	"stt_prop_stunt_bblock_mdm3",
	"stt_prop_stunt_bblock_qp",
	"stt_prop_stunt_bblock_qp2",
	"stt_prop_stunt_bblock_qp3",
	"stt_prop_stunt_bblock_sml1",
	"stt_prop_stunt_bblock_sml2",
	"stt_prop_stunt_bblock_sml3",
	"stt_prop_stunt_bblock_xl1",
	"stt_prop_stunt_bblock_xl2",
	"stt_prop_stunt_bblock_xl3",
	"stt_prop_stunt_bowling_ball",
	"stt_prop_stunt_bowling_pin",
	"stt_prop_stunt_bowling_stand",
	"stt_prop_stunt_domino",
	"stt_prop_stunt_jump15",
	"stt_prop_stunt_jump30",
	"stt_prop_stunt_jump45",
	"stt_prop_stunt_jump_l", 
	"stt_prop_stunt_jump_lb",
	"stt_prop_stunt_jump_loop",
	"stt_prop_stunt_jump_m",
	"stt_prop_stunt_jump_mb",
	"stt_prop_stunt_jump_s",
	"stt_prop_stunt_jump_sb",
	"stt_prop_stunt_jump_sb",
	"stt_prop_stunt_landing_zone_01",
	"stt_prop_stunt_ramp",
	"stt_prop_stunt_soccer_ball",
	"stt_prop_stunt_soccer_goal",
	"stt_prop_stunt_soccer_lball", 
	"stt_prop_stunt_target",
	"stt_prop_stunt_target_small",
	"stt_prop_stunt_track_bumps",
	"apa_prop_aptest",
	"ar_prop_ar_ammu_sign",
	"ar_prop_ar_checkpoint_crn02",
	"stt_prop_stunt_track_cutout",
	"02gate3_l",
	"ar_prop_ar_neon_gate4x_02a",
	"stt_prop_stunt_track_dwlink",
	"stt_prop_stunt_track_dwlink_02",
	"stt_prop_stunt_track_dwsh15",
	"stt_prop_stunt_track_dwshort",
	"stt_prop_stunt_track_dwslope15",
	"stt_prop_stunt_track_dwslope30",
	"stt_prop_stunt_track_dwslope45",
	"stt_prop_stunt_track_dwturn",
	"stt_prop_stunt_track_dwuturn",
	"stt_prop_stunt_track_exshort",
	"stt_prop_stunt_track_fork",
	"stt_prop_stunt_track_funlng", 
	"stt_prop_stunt_track_funnel",
	"stt_prop_stunt_track_hill", 
	"stt_prop_stunt_track_hill2",
	"stt_prop_stunt_track_jump",
	"stt_prop_stunt_track_link",
	"stt_prop_stunt_track_otake",
	"stt_prop_stunt_track_sh15",
	"stt_prop_stunt_track_sh30",
	"stt_prop_stunt_track_sh45",
	"stt_prop_stunt_track_sh45_a",
	"stt_prop_stunt_track_short",
	"stt_prop_stunt_track_slope15",
	"stt_prop_stunt_track_slope30",
	"stt_prop_stunt_track_slope45",
	"stt_prop_stunt_track_start",
	"stt_prop_stunt_track_start_02",
	"stt_prop_stunt_track_straight",
	"stt_prop_stunt_track_straightice",
	"stt_prop_stunt_track_st_01",
	"stt_prop_stunt_track_st_02",
	"stt_prop_stunt_track_turn",
	"stt_prop_stunt_tube_crn",
	"stt_prop_stunt_tube_crn2",
	"stt_prop_stunt_tube_cross",
	"stt_prop_stunt_tube_end",
	"stt_prop_stunt_tube_ent",
	"stt_prop_stunt_tube_fn_01",
	"stt_prop_stunt_tube_fork",
	"stt_prop_stunt_tube_speed",
	"stt_prop_stunt_tube_speeda",
	"stt_prop_stunt_tube_speedb",
	"stt_prop_stunt_wideramp",
	"xs_propintarena_structure_f_01a",
	"xs_propintarena_structure_f_02a",
	"xs_propintarena_structure_f_02b",
	"xs_propintarena_structure_f_02c",
	"xs_propintarena_structure_f_02d",
	"xs_propintarena_structure_f_02e",
	"xs_propintarena_structure_f_03a",
	"xs_propintarena_structure_f_03b",
	"xs_propintarena_structure_f_03c",
	"xs_propintarena_structure_f_03d",
	"xs_propintarena_structure_f_03e",
	"xs_propintarena_structure_f_04a",	
	"prop_med_jet_01",
	"apa_mp_h_kit_kitchen_01_b",
	"sr_prop_spec_tube_xxs_04a",
	"prop_box_wood06a",
	"hei_prop_carrier_radar_1_l1",
	"v_res_mexball",
	"prop_rock_1_a",
	"blimp2",
	"sr_prop_spec_tube_xxs_01a",
	"ar_prop_ar_stunt_block_01a",
	"stt_prop_ramp_adj_flip_m",
	"prop_contnr_pile_01a",
	"ce_xr_ctr2",
	"hei_prop_carrier_jet",
	"stt_prop_stunt_tube_l",
	"stt_prop_ramp_adj_flip_mb",
	"stt_prop_ramp_adj_flip_s",
	"stt_prop_ramp_adj_flip_sb",
	"stt_prop_ramp_adj_hloop",
	"stt_prop_ramp_adj_loop",
	"stt_prop_ramp_jump_l",
	"stt_prop_ramp_jump_m",
	"stt_prop_ramp_jump_s",
	"stt_prop_ramp_jump_xl",
	"stt_prop_ramp_jump_xs",
	"stt_prop_ramp_jump_xxl",
	"stt_prop_ramp_multi_loop_rb",
	"stt_prop_ramp_spiral_l",
	"stt_prop_ramp_spiral_l_l",
	"stt_prop_ramp_spiral_l_m",
	"stt_prop_ramp_spiral_l_s",
	"stt_prop_ramp_spiral_l_xxl",
	"stt_prop_ramp_spiral_m",
	"stt_prop_ramp_spiral_s",
	"stt_prop_ramp_spiral_xxl",
	"prop_fnclink_05crnr1",
	"xs_prop_hamburgher_wl",
	"xs_prop_plastic_bottle_wl",
	"prop_windmill_01",
	"prop_beach_fire",
	"p_spinning_anus_s"
}